module spi_master_fsm(
    input clk,
    input reset,
    input start,
    input slave_select,    // 0 -> Slave0  |  1 -> Slave1
    input [7:0] data_in,         // 8-bit data to transmit
    input miso,            // MISO from selected slave (via top mux)
    output reg mosi,            // Master Out Slave In
    output reg sclk,            // SPI clock (generated by master)
    output reg [1:0] cs,              // Chip-select (active low, 2 slaves)
    output reg done,            // Pulses high for 1 clk when done
    output reg ack,             // 1 = slave ACK (no parity error)
    output reg parity_err_out   // 1 = slave NACK (parity error)
);

parameter IDLE=3'd0,
          LOAD=3'd1,
          TRANSFER=3'd2,
          PARITY=3'd3,
          FEEDBACK=3'd4,
          DONE=3'd5;
reg [2:0] state;

reg [7:0] shift_reg;        // Shift register (data bits)
reg [2:0] bit_count;        // Counts bits sent in TRANSFER (0 to 7)
reg parity_bit;       // Computed even parity = ^data_in
reg feedback_sample;  // 0 = skip first negedge, 1 = sample on next

always @(posedge clk or posedge reset)
begin
    if(reset)
    begin
        state <= IDLE;
        sclk <= 1'b0;
        mosi <= 1'b0;
        cs <= 2'b11;     // Both slaves deselected
        done <= 1'b0;
        ack <= 1'b0;
        parity_err_out <= 1'b0;
        bit_count <= 3'd0;
        shift_reg <= 8'd0;
        parity_bit <= 1'b0;
        feedback_sample <= 1'b0;
    end
    else
    begin
        case(state)

        IDLE:
        begin
            done <= 1'b0;
            sclk <= 1'b0;
            cs <= 2'b11;
            ack <= 0;parity_err_out <= 0;
            if(start)
                state <= LOAD;
        end

        LOAD:
        begin
            // Active-low chip select
            if(slave_select)
                cs <= 2'b01;          // cs[1]=0 : Slave1 selected
            else
                cs <= 2'b10;          // cs[0]=0 : Slave0 selected
            shift_reg  <= data_in;    // Latch 8-bit data
            parity_bit <= ^data_in;   // Even parity bit (9th bit)
            bit_count  <= 0;
            state <= TRANSFER;
        end

        TRANSFER:
        begin
            sclk <= ~sclk;
            if(sclk == 1'b0)          // Setup MOSI before rising edge
            begin
                mosi      <= shift_reg[7];    // MSB first
                shift_reg <= shift_reg << 1;
                bit_count <= bit_count + 1;
                if(bit_count == 7) // Last data bit sent
                    state <= PARITY;
            end
        end

        PARITY:
        begin
            sclk <= ~sclk;
            if(sclk == 1'b0)          // Setup parity bit before rising edge
            begin
                mosi  <= parity_bit;  // 9th bit on MOSI
                state <= FEEDBACK;
            end
        end

        FEEDBACK:
        begin
            sclk <= ~sclk;
            if(sclk == 1'b0)
            begin
                if(feedback_sample == 1'b0)
                begin
                    // Wait one SCLK rising edge for the slave
                    // to update the MISO line.
                    feedback_sample <= 1'b1;
                end
                else
                begin
                    // Slave response is now stable.
                    ack             <= miso;      // 1 = ACK, 0 = NACK
                    parity_err_out  <= ~miso;     // 1 = parity error
                    feedback_sample <= 1'b0;
                    state           <= DONE;
                end
            end
        end

        DONE:
        begin
            cs    <= 2'b11;           // Deselect both slaves
            done  <= 1'b1;
            sclk  <= 1'b0;
            state <= IDLE;
        end
        default: state <= IDLE;
        endcase
    end
end
endmodule
